config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root "movies#index"

  resources :users
  get "signup" => "users#new"

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get "login" => "sessions#new"
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user
  has_many :characterizations, dependent: :destroy
  has_many :genres, through: :characterizations

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :title, :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal: 0 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }
  validates :rating, inclusion: { in: RATINGS }

  def self.released
    where("released_on < ?", Time.now).order(released_on: :desc)
  end

  def self.hits
    where("total_gross >= 300000000").order(total_gross: :desc)
  end

  def self.flops
    where("total_gross < 225000000").order(total_gross: :asc)
  end

  def self.recently_added
    order(created_at: :desc).limit(3)
  end

  def flop?
    if reviews.count > 50 || self.average_stars > 4.0
      false
    else
      total_gross < 225000000 || total_gross.blank?
    end
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end

  def average_stars_as_percent
    (self.average_stars / 5.0) * 100
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @movies = Movie.released.paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html
      format.json {
        render json: { entries: render_to_string(partial: "movies", formats: [:html]), pagination: view_context.will_paginate(@movies) }
      }
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = Movie.includes(:reviews).find(params[:id]).reviews.paginate(page: params[:page], per_page: 5)
    @fans = @movie.fans
    if Current.user
      @favorite = Current.user.favorites.find_by(movie_id: @movie.id)
    end

    respond_to do |format|
      format.html
      format.json {
        render json: { entries: render_to_string(partial: "reviews/reviews", movie: @movie, formats: [:html]), pagination: view_context.will_paginate(@reviews) }
      }
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie), notice: "Movie successfully updated!"
    else
      render :edit
    end

  end

  def new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movie_path(@movie), notice: "Movie successfully created!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to movies_url, alert: "Movie successfully deleted!"
  end

  private

  def movie_params
    params.require(:movie)
          .permit(:title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
    def total_gross(movie)
        if movie.flop?
            "FLOP"
        else
            number_to_currency(movie.total_gross,precision:0)
        end
    end

    def year_of(movie)
        movie.released_on.year
    end
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |f| %>
  <%= render "shared/errors", object: movie %>
  <%= movie.errors.full_messages.to_sentence %>
  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :rating %>
  <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>

  <%= f.label :director %>
  <%= f.text_field :director %>

  <%= f.label :duration %>
  <%= f.text_field :duration %>

  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>

  <%= f.label :released_on %>
  <%= f.date_field :released_on %>

  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>

  <div class="checkboxes">
    <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %>
  </div>

  <%= f.submit %>
<% end %>

app/views/movies/_movies.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <span class="stars">
        <%= render 'shared/stars', percent: movie.average_stars_as_percent %>
      </span>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<div data-controller="infinite-scroll">
  <div data-infinite-scroll-target="entries">
    <%= render 'movies/movies', movies: @movies %>
  </div>
  <div class="lds-roller" id="loading-spinner">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>
  <div style="display: none" data-infinite-scroll-target="pagination">
    <%= will_paginate @movies %>
  </div>
</div>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Movie", new_movie_path(@movie), class: "button" %>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Create a New Movie</h1>

<%= render "form", movie: Movie.new %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>
    <% if Current.user %>
      <div class="faves">
        <%= fave_or_unfave_button(@movie, @favorite) %>
        <div class="count">
          <%= @fans.size %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= year_of(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <div id="review-stars" class="reviews">
      <%= render partial: 'reviews/stars', movie: @movie %>
    </div>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
        <th>Director:</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
    <%= link_to "Write review", new_movie_review_path(@movie), remote: true, class: "review" %>
  </div>
  <aside>
    <% if @fans.present? %>
      <h4>Fans</h4>
      <ul>
        <% @fans.each do |user| %>
          <li>
            <%= link_to user.name, user %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </aside>
</section>
<div id="review-container">
</div>

<div id="reviews" data-controller="infinite-scroll">
  <% if @reviews.any? %>
    <h1>Reviews for <%= @movie.title %> </h1>
    <ul class="reviews" id="review-list" data-infinite-scroll-target="entries">
      <%= render partial: 'reviews/reviews', movie: @movie %>
    </ul>
    <div class="lds-roller" id="loading-spinner">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  <% end %>
  <div style="display: none" data-infinite-scroll-target="pagination">
    <%= will_paginate @reviews %>
  </div>
</div>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
    <%= link_to "Delete", movie_path(@movie), class: "button", method: :delete, data: { confirm: "Are you sure?" } %>
  </section>
<% end %>