config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root "movies#index"

  resources :users
  get "signup" => "users#new"

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get "login" => "sessions#new"
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made by
    <%= link_to 'Harun Sabljakovic', 'https:github.com/sabljak' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo"), root_path %>
    <ul class="left">
      <li>
        <%= link_to 'All Movies', movies_path %>
      </li>
    </ul>
    <ul class="right">
      <% if Current.user %>
        <li>
          <%= link_to Current.user.name, Current.user %>
        </li>
        <li>
          <%= link_to "Account Settings", edit_user_path(Current.user) %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Log In", login_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render "layouts/header" %>

<div class="content">
  <div id="flash-id">
    <%= render "layouts/flash" %>
  </div>
  <%= yield %>
</div>

<%= render "layouts/footer" %>


</body>
</html>